### ISSUE TITLE
Add TypeScript learning resources

### ISSUE THREAD

**Issue by davo** [davo/awesome-react-framer-x#4]
Hello! I'll be adding a section with TypeScript resources later this week.

Found the awesome [React TypeScript Cheatsheet](https://github.com/sw-yx/react-typescript-cheatsheet) list by [@sw-yx](https://github.com/sw-yx).

What other resources are a **must read** for us newbies?

**Comment by tomByrer** [comment]
https://github.com/piotrwitek/react-redux-typescript-guide

**Comment by Caryyon** [comment]
@davo with my PR getting merged, not sure if you wanna keep this issue open?

**Comment by davo** [comment]
Thanks @Caryyon. Closing with #8.
